### ISSUE TITLE
ClientOnlyStream.receiveAndClose(): Cancellation Exception occurring

### ISSUE THREAD

**Issue by Jeremy-Brown14** [connectrpc/connect-kotlin#100]
I'm getting a crash calling this function, occasionally, it doesn't occur every time but it occurs about ⅓ of the time. It seems that if the function doesn't return the resultChannel.receive() in a timely manner, it hits the finally block and cancels the resultChannel, throwing the below exception. Also, shouldn't this function close the messageStream after receiving the result? I have to call the close() function before calling the receiveAndClose() function, otherwise my client doesn't receive from the result channel and send my backend service does not process the resulting stream I sent to it. Thanks for looking into this!

```
FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.cfa.delivery.driver.qa, PID: 20742
    java.util.concurrent.CancellationException: Channel was cancelled
        at kotlinx.coroutines.channels.BufferedChannel.cancelImpl$kotlinx_coroutines_core(BufferedChannel.kt:1765)
        at kotlinx.coroutines.channels.BufferedChannel.cancel(BufferedChannel.kt:1762)
        at kotlinx.coroutines.channels.ReceiveChannel$DefaultImpls.cancel$default(Channel.kt:297)
        at build.buf.connect.impl.ClientOnlyStream.receiveAndClose(ClientOnlyStream.kt:36)
        at build.buf.connect.impl.ClientOnlyStream$receiveAndClose$1.invokeSuspend(Unknown Source:14)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
        at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:100)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by Jeremy-Brown14** [comment]
I have to call close on the stream before calling receiveAndClose(), as our backend service requires the send stream to be closed before it will provide a response, as the receiveAndClose() function does not actually close the stream.

**Comment by Jeremy-Brown14** [comment]
connect-go

**Comment by Jeremy-Brown14** [comment]
I believe what is happening is that it doesn't receive the result in a timely enough manner, as the backend awaits a push notification for the photo URL, and then it hits the finally block and cancels, causing this crash.

**Comment by Jeremy-Brown14** [comment]
Awesome, fix looks great!

**Comment by pkwarren** [comment]
connect-kotlin v0.2.0 is now available with several fixes to streaming (including client streaming). Can you give the new release a try and let me know if it resolves the issues on your side?

**Comment by pkwarren** [comment]
Confirmed this is now working. Closing issue.
