### ISSUE TITLE
Using the Android Studio network inspector crashes the app when performing streaming calls

### ISSUE THREAD

**Issue by ln-12** [connectrpc/connect-kotlin#153]
When the network inspector in Android Studio is active while I perform a connect streaming call, the app just crashes with the following error:
```
E  FATAL EXCEPTION: OkHttp Dispatcher
	Process: com.connectrpc.examples.android, PID: 11743
	java.lang.IllegalStateException: sink already folded
		at okio.Pipe.fold(Pipe.kt:177)
		at com.connectrpc.okhttp.PipeDuplexRequestBody.writeTo(OkHttpStream.kt:211)
		at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:58)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at com.android.tools.profiler.agent.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.java:57)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at com.android.tools.appinspection.network.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.kt:52)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at com.android.tools.profiler.agent.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.java:57)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at com.android.tools.appinspection.network.okhttp.OkHttp3Interceptor.intercept(OkHttp3Interceptor.kt:52)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
		at java.lang.Thread.run(Thread.java:1012)
```

To reproduce, you can simply run the Eliza example from this repo, open the network inspector (wait until it is fully loaded) and open the `Connect - bidirectional streaming` example. The app crashes immediately with the error above.

**Comment by pkwarren** [comment]
I believe this is the same underlying issue as https://issuetracker.google.com/issues/235863810.

**Comment by ln-12** [comment]
Mh, that issue was not updated since over a year... I left a comment there as well as in the linked issue but it seems like that there won't be a solution any time soon.

**Comment by pkwarren** [comment]
There is nothing to be done at the moment for this issue in connect-kotlin (and it does appear to be the same root cause as #154). Interceptor APIs should be updated to look at the duplex/isOneShot settings of the request body and not consume the body in those cases. See https://github.com/square/okhttp/blob/e92667cf828e58a389a28bd2298ede9957c31ed4/okhttp-logging-interceptor/src/main/kotlin/okhttp3/logging/HttpLoggingInterceptor.kt#L198-L201 for an example of the expected handling.

**Comment by ln-12** [comment]
Alright, thanks for looking into it.

For reference, here is the related ticket on the google issue tracker: https://issuetracker.google.com/issues/295991498
