### ISSUE TITLE
IllegalArgumentException: No property for required constructor parameter

### ISSUE THREAD

**Issue by rantianhua** [connectrpc/connect-kotlin#89]
My gradle config

```
android {
    namespace = "xxx"
    compileSdk = 33

    signingConfigs {
        ...
    }

    defaultConfig {
        applicationId = "xxx"
        minSdk = 26
        targetSdk = 33
        versionCode = 1
        versionName = "1.0.0-debug-v10"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
        resourceConfigurations.addAll(listOf("en", "ja", "zh-rCN", "zh-rTW"))
    }

    val useMinifyInDebug = hasProperty("minifyInDebug")

    buildTypes {
        debug {
            isMinifyEnabled = useMinifyInDebug
            isShrinkResources = useMinifyInDebug
            isDebuggable = true
            configure<CrashlyticsExtension> {
                mappingFileUploadEnabled = useMinifyInDebug
            }
            signingConfig = signingConfigs.getByName("debug")
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            configure<CrashlyticsExtension> {
                mappingFileUploadEnabled = true
            }
            signingConfig = signingConfigs.getByName("release")
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
    kotlin {
        jvmToolchain(8)
    }
    buildFeatures {
        compose = true
        viewBinding = true
        buildConfig = true
    }
    composeOptions {
        // https://developer.android.com/jetpack/androidx/releases/compose-kotlin
        kotlinCompilerExtensionVersion = "1.4.8"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {
    implementation("build.buf:connect-kotlin-okhttp:0.1.7")
    implementation("build.buf:connect-kotlin-google-javalite-ext:0.1.7")
}
```

When I build the apk in release buildType with minify enabled. I got the following crash:

```
java.lang.IllegalArgumentException: No property for required constructor parameter #0 code of fun `<init>`(kotlin.String?, kotlin.String?, kotlin.collections.List<build.buf.connect.protocols.ErrorDetailPayloadJSON>?): build.buf.connect.protocols.ErrorPayloadJSON
	at com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory.create(KotlinJsonAdapter.kt:312)
	at com.squareup.moshi.ArrayJsonAdapter$1.create$bridge(ArrayJsonAdapter.java:0)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:106)
	at com.squareup.moshi.Moshi.adapter(Moshi.java:80)
	at build.buf.connect.protocols.ConnectInterceptor.parseConnectUnaryError(ConnectInterceptor.kt:201)
	at build.buf.connect.protocols.ConnectInterceptor.access$parseConnectUnaryError(ConnectInterceptor.kt:40)
	at build.buf.connect.protocols.ConnectInterceptor$unaryFunction$2.invoke(ConnectInterceptor.kt:91)
	at build.buf.connect.protocols.ConnectInterceptor$unaryFunction$2.invoke(ConnectInterceptor.kt:83)
	at build.buf.connect.protocols.ConnectInterceptor$unaryFunction$1.invoke$bridge(ConnectInterceptor.kt:0)
	at build.buf.connect.ProtocolClientConfig$chain$1$unaryFunction$2.invoke(ProtocolClientConfig.kt:129)
	at build.buf.connect.ProtocolClientConfig$chain$1$unaryFunction$2.invoke(ProtocolClientConfig.kt:126)
```

However, when I set `isDebuggable = true`, the crash disappeared.

**Comment by pkwarren** [comment]
It sounds like you may need to customize your proguard-rules.pro file: https://developer.android.com/build/shrink-code#keep-code

It appears to be removing `build.buf.connect.protocols.ErrorPayloadJSON` - you'll likely want to keep that as well as the other classes defined in this file: https://github.com/bufbuild/connect-kotlin/blob/main/library/src/main/kotlin/build/buf/connect/protocols/ErrorJSONModels.kt.

**Comment by pkwarren** [comment]
We've switched from using reflection to using codegen for JSON handling in version 0.1.10. Can you try upgrading to the newer version and see if it helps with this issue?

**Comment by pkwarren** [comment]
Going to go ahead and close this issue. Please re-open if the latest release didn't resolve the issue you were seeing.
